// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: websocket.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Message_Coremessage
	//	*Message_Connectionsetup
	Content       isMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetContent() isMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetCoremessage() *CoreMessage {
	if x != nil {
		if x, ok := x.Content.(*Message_Coremessage); ok {
			return x.Coremessage
		}
	}
	return nil
}

func (x *Message) GetConnectionsetup() *ConnectionSetup {
	if x != nil {
		if x, ok := x.Content.(*Message_Connectionsetup); ok {
			return x.Connectionsetup
		}
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Coremessage struct {
	Coremessage *CoreMessage `protobuf:"bytes,1,opt,name=coremessage,proto3,oneof"`
}

type Message_Connectionsetup struct {
	Connectionsetup *ConnectionSetup `protobuf:"bytes,2,opt,name=connectionsetup,proto3,oneof"`
}

func (*Message_Coremessage) isMessage_Content() {}

func (*Message_Connectionsetup) isMessage_Content() {}

type CoreMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreMessage) Reset() {
	*x = CoreMessage{}
	mi := &file_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreMessage) ProtoMessage() {}

func (x *CoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreMessage.ProtoReflect.Descriptor instead.
func (*CoreMessage) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *CoreMessage) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CoreMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CoreMessage) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConnectionSetup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionSetup) Reset() {
	*x = ConnectionSetup{}
	mi := &file_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSetup) ProtoMessage() {}

func (x *ConnectionSetup) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSetup.ProtoReflect.Descriptor instead.
func (*ConnectionSetup) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionSetup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectionSetup) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_websocket_proto protoreflect.FileDescriptor

const file_websocket_proto_rawDesc = "" +
	"\n" +
	"\x0fwebsocket.proto\"\x84\x01\n" +
	"\aMessage\x120\n" +
	"\vcoremessage\x18\x01 \x01(\v2\f.CoreMessageH\x00R\vcoremessage\x12<\n" +
	"\x0fconnectionsetup\x18\x02 \x01(\v2\x10.ConnectionSetupH\x00R\x0fconnectionsetupB\t\n" +
	"\acontent\"\xb6\x01\n" +
	"\vCoreMessage\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x123\n" +
	"\aoptions\x18\x03 \x03(\v2\x19.CoreMessage.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x0fConnectionSetup\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userIDB\x19Z\x17backend/internal/modelsb\x06proto3"

var (
	file_websocket_proto_rawDescOnce sync.Once
	file_websocket_proto_rawDescData []byte
)

func file_websocket_proto_rawDescGZIP() []byte {
	file_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_proto_rawDesc), len(file_websocket_proto_rawDesc)))
	})
	return file_websocket_proto_rawDescData
}

var file_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_websocket_proto_goTypes = []any{
	(*Message)(nil),         // 0: Message
	(*CoreMessage)(nil),     // 1: CoreMessage
	(*ConnectionSetup)(nil), // 2: ConnectionSetup
	nil,                     // 3: CoreMessage.OptionsEntry
}
var file_websocket_proto_depIdxs = []int32{
	1, // 0: Message.coremessage:type_name -> CoreMessage
	2, // 1: Message.connectionsetup:type_name -> ConnectionSetup
	3, // 2: CoreMessage.options:type_name -> CoreMessage.OptionsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_websocket_proto_init() }
func file_websocket_proto_init() {
	if File_websocket_proto != nil {
		return
	}
	file_websocket_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Coremessage)(nil),
		(*Message_Connectionsetup)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_proto_rawDesc), len(file_websocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_proto_depIdxs,
		MessageInfos:      file_websocket_proto_msgTypes,
	}.Build()
	File_websocket_proto = out.File
	file_websocket_proto_goTypes = nil
	file_websocket_proto_depIdxs = nil
}
