name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Clone the infra repo for workflows etc
        uses: actions/checkout@v3
        with:
          repository: 'unity-sds/unity-cs-infra'
          path: workflowresources

      - name: Build package
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Clone the infra repo for workflows etc
      uses: actions/checkout@v3
      with:
        repository: 'unity-sds/unity-cs-infra'
        path: workflowresources

    - name: Build package
      run: npm run package

    - name: Publish package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: managementconsole.zip
